version: '3.7'
networks:
  mynetwork:
services:
  db:
    image: 'postgres:12.4'
    ports:
      - '5432:5432'
    env_file:
      - './api/.env.development'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'postgres'
    networks:
      - mynetwork

  api:
    build: ./api
    image: livecoding_api
    env_file:
      - './api/.env.development'
    depends_on:
      - db
    ports:
      - '3000:3000'
    links:
      - db
    environment:
      - DB_HOSTNAME=db
      - AUTH_SERVICE_URL=http://auth:3001
    networks:
      - mynetwork

  auth:
    build: ./auth
    image: livecoding_auth
    env_file:
      - './auth/.env.development'
    depends_on:
      - db
    ports:
      - '3001:3001'
    links:
      - db
    environment:
      - DB_HOSTNAME=db
    networks:
      - mynetwork

  migration_api:
    image: livecoding_api
    env_file:
      - './api/.env.development'
    command: ./wait-for-it/wait-for-it.sh -s db:5432 -t 20 -- ./migrate.sh
    links:
      - db
    depends_on:
      - api
      - db
    environment:
      - DB_HOSTNAME=db
    networks:
      - mynetwork

  migration_auth:
    image: livecoding_auth
    env_file:
      - './auth/.env.development'

    command: ./wait-for-it/wait-for-it.sh -s db:5432 -t 20 -- ./migrate.sh
    links:
      - db
    depends_on:
      - auth
      - db
    environment:
      - DB_HOSTNAME=db
    networks:
      - mynetwork

  nginx:
    image: nginx
    hostname: nginx
    depends_on:
      - api
      - auth
    ports:
      - '4000:4000'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - mynetwork
