'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('people', [
      {
        gender: 'male',
        id: 1,
        skin_color: 'fair',
        name: 'Luke Skywalker',
        height: 172,
        mass: 77,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        gender: 'n/a',
        id: 2,
        skin_color: 'gold',
        name: 'C-3PO',
        height: 167,
        mass: 75,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        gender: 'n/a',
        id: 3,
        skin_color: 'white, blue',
        name: 'R2-D2',
        height: 96,
        mass: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        gender: 'male',
        id: 4,
        skin_color: 'white',
        name: 'Darth Vader',
        height: 202,
        mass: 136,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        gender: 'female',
        id: 5,
        skin_color: 'light',
        name: 'Leia Organa',
        height: 150,
        mass: 49,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        gender: 'male',
        id: 6,
        skin_color: 'light',
        name: 'Owen Lars',
        height: 178,
        mass: 120,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        gender: 'female',
        id: 7,
        skin_color: 'light',
        name: 'Beru Whitesun lars',
        height: 165,
        mass: 75,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        gender: 'n/a',
        id: 8,
        skin_color: 'white, red',
        name: 'R5-D4',
        height: 97,
        mass: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        gender: 'male',
        id: 9,
        skin_color: 'light',
        name: 'Biggs Darklighter',
        height: 183,
        mass: 84,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        gender: 'male',
        id: 10,
        skin_color: 'fair',
        name: 'Obi-Wan Kenobi',
        height: 182,
        mass: 77,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('people', null, {});
  },
};
